import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | MahaTathastu',
  description: 'Terms and conditions for using MahaTathastu - India\'s 360° Holistic Life Platform.',
}

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: `By creating an account or using any feature of MahaTathastu ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Platform.

MahaTathastu is operated by Levitate Labs ("we", "us", "our"). These terms constitute a legally binding agreement between you and Levitate Labs under Indian law.`,
  },
  {
    id: 'account',
    title: '2. Account Terms',
    content: `**Eligibility:** You must be at least 13 years of age to create an account. By registering, you represent that you meet this requirement.

**Account Security:** You are responsible for maintaining the confidentiality of your login credentials. You must notify us immediately at support@mahatathastu.com if you suspect unauthorized access to your account.

**Accurate Information:** You agree to provide accurate, complete information when registering and to keep your account information updated.

**One Account Per Person:** Each individual should maintain only one account. Creating multiple accounts to circumvent restrictions or obtain multiple trial benefits is prohibited.`,
  },
  {
    id: 'services',
    title: '3. Our Services',
    content: `MahaTathastu provides AI-powered Vedic report generation, live Panchang calculations, spiritual guidance tools, and an e-commerce platform for spiritual products.

**Nature of Reports:** Our Vedic reports are generated by AI systems trained on classical Jyotish, Numerology, Ayurveda, and related sciences. They are provided for **informational and guidance purposes only** and do not constitute:
- Medical advice or diagnosis
- Legal, financial, or professional advice
- Guarantee of any future events or outcomes

**Report Accuracy:** We strive for accuracy in all calculations. However, the quality of reports depends on the accuracy of birth details you provide. We are not liable for inaccuracies resulting from incorrect birth information.`,
  },
  {
    id: 'payment',
    title: '4. Payment & Refund Policy',
    content: `**Pricing:** All prices are listed in Indian Rupees (INR) and are inclusive of applicable taxes.

**Payment Processing:** All payments are processed by Razorpay, a PCI-DSS compliant payment gateway. We do not store your payment card details.

**Digital Products - No Refund Policy:** Since Vedic reports are generated immediately upon purchase and you receive instant access to the digital content, we generally do not offer refunds for completed report purchases.

**Exceptions:** We will provide a full refund if:
- The report was not generated due to a technical error on our side
- You were charged twice for the same report
- The report contains a fundamental calculation error (wrong chart/nakshatra)

To request a refund, contact support@mahatathastu.com within 48 hours of purchase with your order number.

**Physical Products:** For physical items (yantras, gemstones, etc.), we accept returns within 7 days of delivery if the item is damaged or not as described.`,
  },
  {
    id: 'ip',
    title: '5. Intellectual Property',
    content: `**Our Content:** All content on MahaTathastu - including AI-generated reports, software, design, text, graphics, and brand materials - is the intellectual property of Levitate Labs and is protected under Indian copyright law.

**Your Reports:** The Vedic reports generated for your birth data are licensed to you for personal use. You may download and share your own reports. You may not resell, redistribute, or create derivative works from our reports without written permission.

**Your Content:** By adding content to the Platform (profile photos, testimonials, etc.), you grant us a non-exclusive license to display that content on the Platform.`,
  },
  {
    id: 'prohibited',
    title: '6. Prohibited Uses',
    content: `You agree not to:

- Use the Platform to generate reports for commercial resale without our written authorization
- Attempt to reverse-engineer, scrape, or extract our AI models or report generation logic
- Use automated tools (bots, scrapers) to access the Platform
- Impersonate another person or misrepresent your affiliation
- Upload malicious code or attempt to compromise Platform security
- Use the Platform for any unlawful purpose under Indian law
- Harass, abuse, or harm other users of the Platform

Violation of these terms may result in immediate account termination without refund.`,
  },
  {
    id: 'disclaimer',
    title: '7. Disclaimers & Limitation of Liability',
    content: `**As-Is Service:** The Platform is provided "as is" without warranty of any kind. We do not guarantee uninterrupted availability or error-free operation.

**Limitation:** To the maximum extent permitted under Indian law, Levitate Labs shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the Platform.

**Cap:** Our total liability to you for any claim shall not exceed the amount you paid to us in the three months preceding the claim.

**Force Majeure:** We are not liable for service disruptions caused by circumstances beyond our control (internet outages, natural disasters, government actions, etc.).`,
  },
  {
    id: 'governing',
    title: '8. Governing Law & Disputes',
    content: `These Terms are governed by and construed in accordance with the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of Jammu, Jammu & Kashmir, India.

**Dispute Resolution:** We encourage you to first contact us at support@mahatathastu.com to resolve any issue informally before initiating legal proceedings. We commit to responding to all disputes within 14 business days.`,
  },
  {
    id: 'changes',
    title: '9. Changes to Terms',
    content: `We may revise these Terms from time to time. We will notify you of material changes by email at least 14 days before they take effect. Your continued use of the Platform after the effective date constitutes your acceptance of the revised Terms.

For questions about these Terms, contact us at legal@mahatathastu.com.`,
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--kutch-white)]">
      <section className="page-banner">
        <div className="page-banner-inner max-w-2xl mx-auto">
          <p className="text-[var(--saffron)] text-xs font-bold tracking-[0.2em] uppercase mb-4" style={{ fontFamily: "'Sora', sans-serif" }}>Legal</p>
          <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4 leading-tight" style={{ fontFamily: "'Playfair Display', serif" }}>Terms of Service</h1>
          <div className="ornate-divider">
            <span className="material-symbols-outlined text-[14px] text-[var(--terracotta)]" style={{ fontVariationSettings: "'FILL' 1" }}>diamond</span>
          </div>
          <p className="text-white/65 text-base">Effective: 1 June 2025 &nbsp;&middot;&nbsp; Last updated: 18 June 2026</p>
        </div>
      </section>

      <section className="py-14 px-6">
        <div className="max-w-3xl mx-auto">
          <div className="card-divine p-6 mb-10" style={{ background: 'linear-gradient(135deg, #FEF5EC, #FFF8E1)', borderColor: '#E8D5A0' }}>
            <p className="text-[var(--warm-charcoal)]/80 leading-relaxed text-sm">
              Please read these terms carefully before using MahaTathastu. These terms govern your access to and use of our platform, services, and products. By using MahaTathastu, you agree to be bound by these terms.
            </p>
          </div>

          <div className="space-y-10">
            {SECTIONS.map(sec => (
              <div key={sec.id} id={sec.id}>
                <h2 className="text-xl font-bold text-[var(--indigo-deep)] mb-4" style={{ fontFamily: "'Playfair Display', serif" }}>{sec.title}</h2>
                <div className="text-sm text-[var(--warm-charcoal)]/75 leading-relaxed space-y-3">
                  {sec.content.split('\n\n').map((para, i) => (
                    <p key={i}
                      dangerouslySetInnerHTML={{
                        __html: para
                          .replace(/\*\*(.+?)\*\*/g, '<strong class="text-[var(--indigo-deep)]">$1</strong>')
                          .replace(/\n/g, '<br/>'),
                      }}
                    />
                  ))}
                </div>
                <div className="h-px bg-[var(--warm-sand)] mt-10" />
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  )
}
