// Mantra Science — Planet → Deity → Mantra mapping

const PLANET_MANTRA_DATA: Record<string, {
  beejMantra: string; planetMantra: string; deity: string; deityMantra: string;
  count: number[]; bestTime: string; bestDay: string; direction: string;
  mala: string; sitPosition: string; mahaMantra: string; likhitJapa: {
    mantra: string; count: number; pen: string; paper: string; inkColor: string
    posture: string; auspiciousDays: string[]
  }
}> = {
  Sun: {
    beejMantra: 'ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः',
    planetMantra: 'ॐ सूर्याय नमः',
    deity: 'Lord Surya / Lord Rama',
    deityMantra: 'ॐ रामाय नमः',
    count: [108, 1008, 21],
    bestTime: 'Sunrise (Brahma Muhurta)',
    bestDay: 'Sunday',
    direction: 'East',
    mala: 'Rudraksha mala or copper mala',
    sitPosition: 'Face East, sit on red cloth',
    mahaMantra: 'ॐ ह्रां ह्रीं ह्रौं सः सूर्याय नमः | आदित्याय नमः',
    likhitJapa: {
      mantra: 'ॐ सूर्याय नमः',
      count: 108,
      pen: 'Red ink pen',
      paper: 'Yellow paper',
      inkColor: 'Red or saffron',
      posture: 'Sit facing East on a red mat',
      auspiciousDays: ['Sunday', 'Ekadashi', 'Purnima'],
    },
  },
  Moon: {
    beejMantra: 'ॐ श्रां श्रीं श्रौं सः चन्द्राय नमः',
    planetMantra: 'ॐ चन्द्राय नमः',
    deity: 'Lord Shiva / Goddess Parvati',
    deityMantra: 'ॐ नमः शिवाय',
    count: [108, 11],
    bestTime: 'Monday evening / Full moon night',
    bestDay: 'Monday',
    direction: 'North-West',
    mala: 'Pearl mala or white sandalwood mala',
    sitPosition: 'Face North-West, sit on white cloth',
    mahaMantra: 'ॐ श्रां श्रीं श्रौं सः चन्द्राय नमः',
    likhitJapa: {
      mantra: 'ॐ चन्द्राय नमः',
      count: 108,
      pen: 'Silver ink pen',
      paper: 'White paper',
      inkColor: 'White or silver',
      posture: 'Sit facing North on a white mat',
      auspiciousDays: ['Monday', 'Purnima', 'Ekadashi'],
    },
  },
  Mars: {
    beejMantra: 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः',
    planetMantra: 'ॐ मंगलाय नमः',
    deity: 'Lord Hanuman / Lord Kartikeya',
    deityMantra: 'ॐ हं हनुमते नमः',
    count: [108, 21],
    bestTime: 'Tuesday Sunrise',
    bestDay: 'Tuesday',
    direction: 'South',
    mala: 'Red sandalwood mala or coral mala',
    sitPosition: 'Face South, sit on red cloth',
    mahaMantra: 'ॐ क्रां क्रीं क्रौं सः भौमाय नमः',
    likhitJapa: {
      mantra: 'ॐ मंगलाय नमः',
      count: 108,
      pen: 'Red pen',
      paper: 'Red paper',
      inkColor: 'Red',
      posture: 'Sit facing South on a red mat, Tuesday morning',
      auspiciousDays: ['Tuesday', 'Navratri days'],
    },
  },
  Mercury: {
    beejMantra: 'ॐ ब्रां ब्रीं ब्रौं सः बुधाय नमः',
    planetMantra: 'ॐ बुधाय नमः',
    deity: 'Lord Vishnu / Goddess Saraswati',
    deityMantra: 'ॐ नमो भगवते वासुदेवाय',
    count: [108, 21],
    bestTime: 'Wednesday morning',
    bestDay: 'Wednesday',
    direction: 'North',
    mala: 'Green jade mala or emerald mala',
    sitPosition: 'Face North, sit on green cloth',
    mahaMantra: 'ॐ ब्रां ब्रीं ब्रौं सः बुधाय नमः | ॐ ऐं सरस्वत्यै नमः',
    likhitJapa: {
      mantra: 'ॐ बुधाय नमः',
      count: 108,
      pen: 'Green ink pen',
      paper: 'Green or white paper',
      inkColor: 'Green',
      posture: 'Sit facing North on a green mat, Wednesday morning',
      auspiciousDays: ['Wednesday', 'Panchami', 'Chaturthi'],
    },
  },
  Jupiter: {
    beejMantra: 'ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः',
    planetMantra: 'ॐ गुरवे नमः',
    deity: 'Lord Vishnu / Lord Dattatreya',
    deityMantra: 'ॐ नमो भगवते वासुदेवाय | ॐ द्रां दत्तात्रेयाय नमः',
    count: [108, 16, 1008],
    bestTime: 'Thursday Sunrise',
    bestDay: 'Thursday',
    direction: 'North-East',
    mala: 'Yellow sapphire mala or sandalwood mala',
    sitPosition: 'Face North-East, sit on yellow cloth',
    mahaMantra: 'ॐ ग्रां ग्रीं ग्रौं सः गुरवे नमः',
    likhitJapa: {
      mantra: 'ॐ गुरवे नमः',
      count: 108,
      pen: 'Yellow or gold ink pen',
      paper: 'Yellow paper',
      inkColor: 'Yellow or golden',
      posture: 'Sit facing North-East on a yellow mat, Thursday morning',
      auspiciousDays: ['Thursday', 'Ekadashi', 'Purnima'],
    },
  },
  Venus: {
    beejMantra: 'ॐ द्रां द्रीं द्रौं सः शुक्राय नमः',
    planetMantra: 'ॐ शुक्राय नमः',
    deity: 'Goddess Lakshmi / Goddess Durga',
    deityMantra: 'ॐ श्रीं महालक्ष्म्यै नमः',
    count: [108, 21],
    bestTime: 'Friday morning',
    bestDay: 'Friday',
    direction: 'South-East',
    mala: 'White sandalwood mala or diamond/crystal mala',
    sitPosition: 'Face South-East, sit on white or pink cloth',
    mahaMantra: 'ॐ द्रां द्रीं द्रौं सः शुक्राय नमः | ॐ श्रीं ह्रीं श्रीं महालक्ष्म्यै नमः',
    likhitJapa: {
      mantra: 'ॐ शुक्राय नमः',
      count: 108,
      pen: 'White or pink ink pen',
      paper: 'White paper',
      inkColor: 'White, pink, or rose',
      posture: 'Sit facing East on a white mat, Friday morning',
      auspiciousDays: ['Friday', 'Purnima', 'Navratri'],
    },
  },
  Saturn: {
    beejMantra: 'ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः',
    planetMantra: 'ॐ शनैश्चराय नमः',
    deity: 'Lord Shani / Lord Bhairav',
    deityMantra: 'ॐ शं शनैश्चराय नमः',
    count: [108, 19, 23],
    bestTime: 'Saturday at sunset',
    bestDay: 'Saturday',
    direction: 'West',
    mala: 'Iron mala or black sesame mala',
    sitPosition: 'Face West, sit on black or dark blue cloth',
    mahaMantra: 'ॐ प्रां प्रीं प्रौं सः शनैश्चराय नमः',
    likhitJapa: {
      mantra: 'ॐ शनैश्चराय नमः',
      count: 108,
      pen: 'Black ink pen',
      paper: 'Blue or black paper',
      inkColor: 'Dark blue or black',
      posture: 'Sit facing West on a black mat, Saturday evening',
      auspiciousDays: ['Saturday', 'Amavasya', 'Shani Jayanti'],
    },
  },
  Rahu: {
    beejMantra: 'ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः',
    planetMantra: 'ॐ राहवे नमः',
    deity: 'Goddess Durga / Lord Bhairav',
    deityMantra: 'ॐ दुं दुर्गायै नमः',
    count: [108, 18],
    bestTime: 'Saturday night or sunset',
    bestDay: 'Saturday',
    direction: 'South-West',
    mala: 'Black glass bead mala or Rahu mala',
    sitPosition: 'Face South-West, sit on dark cloth',
    mahaMantra: 'ॐ भ्रां भ्रीं भ्रौं सः राहवे नमः',
    likhitJapa: {
      mantra: 'ॐ राहवे नमः',
      count: 108,
      pen: 'Dark blue or black ink pen',
      paper: 'Dark blue paper',
      inkColor: 'Dark blue',
      posture: 'Sit facing South-West on a dark mat, Saturday night',
      auspiciousDays: ['Saturday', 'Rahu Kaal timing', 'Amavasya'],
    },
  },
  Ketu: {
    beejMantra: 'ॐ स्रां स्रीं स्रौं सः केतवे नमः',
    planetMantra: 'ॐ केतवे नमः',
    deity: 'Lord Ganesha / Lord Skanda',
    deityMantra: 'ॐ गं गणपतये नमः',
    count: [108, 7],
    bestTime: 'Tuesday or Saturday sunrise',
    bestDay: 'Tuesday',
    direction: 'North-West',
    mala: 'Cat eye mala or Ketu mala',
    sitPosition: 'Face North-West, sit on grey or mixed cloth',
    mahaMantra: 'ॐ स्रां स्रीं स्रौं सः केतवे नमः',
    likhitJapa: {
      mantra: 'ॐ केतवे नमः',
      count: 108,
      pen: 'Brown ink pen',
      paper: 'Brown or grey paper',
      inkColor: 'Brown',
      posture: 'Sit facing North on an earth-tone mat, Tuesday morning',
      auspiciousDays: ['Tuesday', 'Chaturdashi', 'Amavasya'],
    },
  },
}

const NAKSHATRA_BEEJ: Record<string, string> = {
  'Ashwini': 'ॐ अश्विनी देव्यै नमः',
  'Bharani': 'ॐ यमाय नमः',
  'Krittika': 'ॐ अग्नये नमः',
  'Rohini': 'ॐ ब्राह्मणे नमः',
  'Mrigashira': 'ॐ चन्द्राय नमः',
  'Ardra': 'ॐ रुद्राय नमः',
  'Punarvasu': 'ॐ अदितये नमः',
  'Pushya': 'ॐ बृहस्पतये नमः',
  'Ashlesha': 'ॐ सर्पेभ्यो नमः',
  'Magha': 'ॐ पितृभ्यो नमः',
  'Purva Phalguni': 'ॐ भगाय नमः',
  'Uttara Phalguni': 'ॐ अर्यम्णे नमः',
  'Hasta': 'ॐ सवित्रे नमः',
  'Chitra': 'ॐ त्वष्ट्रे नमः',
  'Swati': 'ॐ वायवे नमः',
  'Vishakha': 'ॐ इन्द्राग्निभ्यां नमः',
  'Anuradha': 'ॐ मित्राय नमः',
  'Jyeshtha': 'ॐ इन्द्राय नमः',
  'Moola': 'ॐ निरृत्यै नमः',
  'Purva Ashadha': 'ॐ अपां पत्ये नमः',
  'Uttara Ashadha': 'ॐ विश्वेभ्यो देवेभ्यो नमः',
  'Shravana': 'ॐ विष्णवे नमः',
  'Dhanishtha': 'ॐ अष्टवसुभ्यो नमः',
  'Shatabhisha': 'ॐ वरुणाय नमः',
  'Purva Bhadrapada': 'ॐ अजैकपादाय नमः',
  'Uttara Bhadrapada': 'ॐ अहिर्बुध्न्याय नमः',
  'Revati': 'ॐ पूष्णे नमः',
}

export function calculateMantraGuidance(
  dashaLord: string,
  nakshatra: string,
  ascendant: string,
  moonSign: string,
) {
  const primaryData = PLANET_MANTRA_DATA[dashaLord] || PLANET_MANTRA_DATA.Jupiter
  const nakshatraBeej = NAKSHATRA_BEEJ[nakshatra] || 'ॐ नमः शिवाय'

  return {
    chanting: {
      primaryPlanet: dashaLord,
      beejMantra: primaryData.beejMantra,
      planetMantra: primaryData.planetMantra,
      deity: primaryData.deity,
      deityMantra: primaryData.deityMantra,
      nakshatraMantra: nakshatraBeej,
      mahaMantra: primaryData.mahaMantra,
      dailyCount: primaryData.count[0],
      weeklyCount: primaryData.count[1] || primaryData.count[0] * 7,
      bestTime: primaryData.bestTime,
      bestDay: primaryData.bestDay,
      direction: primaryData.direction,
      mala: primaryData.mala,
      posture: primaryData.sitPosition,
      sequence: [
        'Purify hands and face',
        'Light a ghee lamp or candle',
        'Face ' + primaryData.direction,
        'Chant "OM" 3 times to purify the space',
        'Chant the beej mantra: ' + primaryData.beejMantra,
        'Chant the planet mantra ' + primaryData.count[0] + ' times',
        'Conclude with the deity mantra',
        'Sit in silence for 5 minutes',
      ],
    },
    likhitJapa: {
      ...primaryData.likhitJapa,
      nakshatraMantra: nakshatraBeej,
      instructions: [
        'Wake before sunrise on ' + primaryData.likhitJapa.auspiciousDays[0],
        'Bathe and wear clean clothes',
        'Sit in ' + primaryData.likhitJapa.posture,
        'Use ' + primaryData.likhitJapa.pen + ' on ' + primaryData.likhitJapa.paper,
        'Write the mantra ' + primaryData.likhitJapa.count + ' times in a dedicated notebook',
        'Keep the notebook wrapped in clean cloth when not in use',
        'Offer the written pages to a river or sacred fire after 40 days',
      ],
    },
  }
}
